name: Контроль качества

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sonar:
    if: github.repository_owner == 'stivo182'
    uses: Stivo182/oscript-workflows/.github/workflows/sonar-dotnet.yml@main
    with:
      github_repository: Stivo182/BenchmarkOneScript
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
